"use client";

import { CheckCircle2, ClipboardCheck, Plus, ShieldAlert, XCircle } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Modal, fieldInput, fieldLabel } from "@/components/ui/Modal";
import { insight } from "@/lib/insight";

type Cycle={id:string;name:string;scope_location?:string;start_date:string;end_date:string;status:string;counts:Record<"pending"|"verified"|"missing"|"damaged",number>;auditor_ids:string[]};
type Item={id:string;asset_tag:string;asset_name:string;location?:string;result:string;notes:string};
const resultStyle:Record<string,string>={pending:"bg-surface-container text-on-surface-variant",verified:"bg-emerald-active/10 text-emerald-active",missing:"bg-status-critical/10 text-status-critical",damaged:"bg-status-warning/10 text-status-warning"};

export default function AuditPage(){
 const [cycles,setCycles]=useState<Cycle[]>([]),[selected,setSelected]=useState<Cycle|null>(null),[items,setItems]=useState<Item[]>([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 const load=()=>insight<Cycle[]>("/audits").then(rows=>{setCycles(rows);if(selected)setSelected(rows.find(x=>x.id===selected.id)||null)}).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]); useEffect(()=>{if(selected)insight<Item[]>(`/audits/${selected.id}/items`).then(setItems).catch(e=>setError(e.message))},[selected]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await insight("/audits",{method:"POST",body:JSON.stringify({...d,auditor_ids:String(d.auditor_ids||"").split(",").map(x=>x.trim()).filter(Boolean),scope_dept_id:d.scope_dept_id||null,scope_location:d.scope_location||null})});setOpen(false);load()}catch(e){setError((e as Error).message)}}
 async function mark(item:Item,result:string){await insight(`/audits/items/${item.id}`,{method:"PATCH",body:JSON.stringify({result,notes:item.notes})});if(selected)setItems(await insight(`/audits/${selected.id}/items`))}
 async function close(){if(!selected)return;try{await insight(`/audits/${selected.id}/close`,{method:"POST"});setSelected(null);load()}catch(e){setError((e as Error).message)}}
 return <div className="mx-auto max-w-[1440px] space-y-lg p-lg md:p-xl"><header className="flex items-end justify-between"><div><p className="font-label-caps text-label-caps font-semibold text-indigo-accent">PHYSICAL VERIFICATION</p><h1 className="font-display-lg text-display-lg">Asset audits</h1><p className="text-on-surface-variant">Verify custody, surface discrepancies, and close the loop.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-xs rounded-DEFAULT bg-deep-navy px-md py-2 text-white"><Plus className="h-4 w-4"/>New cycle</button></header>{error&&<div role="alert" className="rounded-DEFAULT bg-status-critical/10 p-md text-status-critical">{error}</div>}
 <section className="grid gap-lg lg:grid-cols-[360px_1fr]"><aside className="space-y-sm">{cycles.length?cycles.map(c=>{const total=Object.values(c.counts).reduce((a,b)=>a+b,0),done=total-c.counts.pending;return <button key={c.id} onClick={()=>setSelected(c)} className={`w-full rounded-DEFAULT border bg-surface p-md text-left shadow-card ${selected?.id===c.id?"border-indigo-accent":"border-border-muted"}`}><div className="flex justify-between"><b>{c.name}</b><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${c.status==="open"?"bg-emerald-active/10 text-emerald-active":"bg-surface-container"}`}>{c.status}</span></div><p className="my-sm text-sm text-on-surface-variant">{c.scope_location||"All locations"} · {c.start_date}</p><div className="h-1.5 overflow-hidden rounded-full bg-surface-container"><div className="h-full bg-indigo-accent" style={{width:`${total?done/total*100:0}%`}}/></div><small className="mt-xs block">{done}/{total} checked</small></button>}):<div className="rounded-DEFAULT border border-dashed border-border-muted p-xl text-center text-on-surface-variant">No audit cycles yet.</div>}</aside>
 <article className="overflow-hidden rounded-DEFAULT border border-border-muted bg-surface shadow-card">{selected?<><div className="flex items-center justify-between border-b border-border-muted p-md"><div><h2 className="font-headline-sm text-headline-sm">{selected.name}</h2><p className="text-sm text-on-surface-variant">{items.length} assets in scope</p></div>{selected.status==="open"&&<button onClick={close} className="rounded-DEFAULT bg-emerald-active px-md py-2 text-sm font-semibold text-white">Close cycle</button>}</div><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-surface-subtle text-xs uppercase text-on-surface-variant"><tr><th className="p-md">Asset</th><th>Location</th><th>Result</th><th className="text-right">Verify</th></tr></thead><tbody className="divide-y divide-border-muted">{items.map(i=><tr key={i.id}><td className="p-md"><b className="block">{i.asset_name}</b><code className="text-xs text-indigo-accent">{i.asset_tag}</code></td><td>{i.location||"—"}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold capitalize ${resultStyle[i.result]}`}>{i.result}</span></td><td><div className="flex justify-end gap-xs pr-md">{selected.status==="open"&&<><button title="Verified" aria-label={`Mark ${i.asset_tag} verified`} onClick={()=>mark(i,"verified")} className="rounded p-1 text-emerald-active hover:bg-emerald-active/10"><CheckCircle2/></button><button title="Missing" aria-label={`Mark ${i.asset_tag} missing`} onClick={()=>mark(i,"missing")} className="rounded p-1 text-status-critical hover:bg-status-critical/10"><XCircle/></button><button title="Damaged" aria-label={`Mark ${i.asset_tag} damaged`} onClick={()=>mark(i,"damaged")} className="rounded p-1 text-status-warning hover:bg-status-warning/10"><ShieldAlert/></button></>}</div></td></tr>)}</tbody></table></div></>:<div className="grid min-h-96 place-items-center p-xl text-center text-on-surface-variant"><div><ClipboardCheck className="mx-auto mb-md h-10 w-10"/><p>Select an audit cycle to review its assets.</p></div></div>}</article></section>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create audit cycle"><form onSubmit={create} className="space-y-md"><label className={fieldLabel}>Cycle name<input className={fieldInput} name="name" required/></label><div className="grid grid-cols-2 gap-sm"><label className={fieldLabel}>Start<input className={fieldInput} name="start_date" type="date" required/></label><label className={fieldLabel}>End<input className={fieldInput} name="end_date" type="date" required/></label></div><label className={fieldLabel}>Location scope<input className={fieldInput} name="scope_location" placeholder="Blank means all"/></label><label className={fieldLabel}>Department ID<input className={fieldInput} name="scope_dept_id"/></label><label className={fieldLabel}>Auditor IDs<input className={fieldInput} name="auditor_ids" placeholder="Comma-separated employee IDs"/></label><div className="flex justify-end gap-sm pt-md"><button type="button" onClick={()=>setOpen(false)} className="rounded-DEFAULT border border-border-muted px-md py-2">Cancel</button><button className="rounded-DEFAULT bg-deep-navy px-md py-2 text-white">Create cycle</button></div></form></Modal>
 </div>
}
