"use client";

import { Download, MapPin, PieChart } from "lucide-react";
import { useEffect, useState } from "react";
import { insight } from "@/lib/insight";

type Row={label:string;value:number}; type Report={total:number;statuses:Row[];locations:Row[];categories:Row[];maintenance_frequency:Row[]};
function Bars({rows,total}:{rows:Row[];total:number}){return <div className="space-y-md">{rows.map(x=><div key={x.label}><div className="mb-xs flex justify-between text-sm"><span className="capitalize">{x.label.replaceAll("_"," ")}</span><b>{x.value}</b></div><div className="h-2 overflow-hidden rounded-full bg-surface-container"><div className="h-full rounded-full bg-indigo-accent" style={{width:`${total?Math.max(4,x.value/total*100):0}%`}}/></div></div>)}</div>}
export default function ReportsPage(){
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(""); useEffect(()=>{insight<Report>("/reports").then(setData).catch(e=>setError(e.message))},[]);
 function download(){const token=localStorage.getItem("token"); fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/insight/reports/assets.csv`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.blob()).then(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="assetflow-assets.csv";a.click();URL.revokeObjectURL(a.href)})}
 return <div className="mx-auto max-w-[1440px] space-y-lg p-lg md:p-xl"><header className="flex items-end justify-between"><div><p className="font-label-caps text-label-caps font-semibold text-indigo-accent">INSIGHT</p><h1 className="font-display-lg text-display-lg">Reports & analytics</h1><p className="text-on-surface-variant">Portfolio distribution, utilization and operating footprint.</p></div><button onClick={download} className="flex items-center gap-xs rounded-DEFAULT bg-deep-navy px-md py-2 text-white"><Download className="h-4 w-4"/>Export CSV</button></header>{error&&<p role="alert" className="text-status-critical">{error}</p>}{!data?<div className="h-48 animate-pulse bg-surface-container"/>:<><section className="grid gap-md md:grid-cols-3"><article className="rounded-DEFAULT border border-border-muted bg-deep-navy p-lg text-white"><PieChart className="mb-lg text-emerald-active"/><b className="font-display-lg text-display-lg">{data.total}</b><p className="text-slate-300">Assets tracked</p></article><article className="rounded-DEFAULT border border-border-muted bg-surface p-lg md:col-span-2"><h2 className="mb-lg font-headline-sm text-headline-sm">Lifecycle mix</h2><Bars rows={data.statuses} total={data.total}/></article></section><section className="grid gap-lg md:grid-cols-2"><article className="rounded-DEFAULT border border-border-muted bg-surface p-lg"><h2 className="mb-lg flex items-center gap-sm font-headline-sm text-headline-sm"><MapPin className="text-emerald-active"/>Location heatmap</h2><Bars rows={data.locations} total={data.total}/></article><article className="rounded-DEFAULT border border-border-muted bg-surface p-lg"><h2 className="mb-lg font-headline-sm text-headline-sm">Category distribution</h2><Bars rows={data.categories} total={data.total}/></article></section><section className="rounded-DEFAULT border border-border-muted bg-surface p-lg"><h2 className="mb-lg font-headline-sm text-headline-sm">Maintenance frequency</h2>{data.maintenance_frequency.length?<Bars rows={data.maintenance_frequency} total={Math.max(...data.maintenance_frequency.map(x=>x.value))}/>:<p className="text-on-surface-variant">Maintenance events will rank here as work is completed.</p>}</section></>}</div>
}
