"use client";

import { Bell, CheckCheck, History } from "lucide-react";
import { useEffect, useState } from "react";
import { dateTime, insight } from "@/lib/insight";
type Notice={id:string;type:string;message:string;is_read:boolean;created_at:string}; type Log={id:string;actor:string;action:string;entity_type:string;entity_id:string;timestamp:string};
export default function NotificationsPage(){const [tab,setTab]=useState<"notifications"|"activity">("notifications"),[notices,setNotices]=useState<Notice[]>([]),[logs,setLogs]=useState<Log[]>([]),[error,setError]=useState(""); const load=()=>Promise.all([insight<Notice[]>("/notifications"),insight<Log[]>("/activity")]).then(([n,l])=>{setNotices(n);setLogs(l)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const readAll=()=>insight("/notifications/read-all",{method:"POST"}).then(load); const read=(id:string)=>insight(`/notifications/${id}/read`,{method:"PATCH"}).then(load);
 return <div className="mx-auto max-w-[1200px] space-y-lg p-lg md:p-xl"><header><p className="font-label-caps text-label-caps font-semibold text-indigo-accent">SYSTEM FEED</p><h1 className="font-display-lg text-display-lg">Notifications & activity</h1></header><div className="flex items-center justify-between border-b border-border-muted"><div className="flex gap-lg"><button onClick={()=>setTab("notifications")} className={`flex gap-xs border-b-2 px-xs py-sm font-semibold ${tab==="notifications"?"border-indigo-accent text-indigo-accent":"border-transparent"}`}><Bell className="h-4 w-4"/>Notifications</button><button onClick={()=>setTab("activity")} className={`flex gap-xs border-b-2 px-xs py-sm font-semibold ${tab==="activity"?"border-indigo-accent text-indigo-accent":"border-transparent"}`}><History className="h-4 w-4"/>Activity log</button></div>{tab==="notifications"&&<button onClick={readAll} className="flex gap-xs text-sm font-semibold text-indigo-accent"><CheckCheck className="h-4 w-4"/>Mark all read</button>}</div>{error&&<p role="alert" className="text-status-critical">{error}</p>}<section className="overflow-hidden rounded-DEFAULT border border-border-muted bg-surface">{tab==="notifications"?<ul className="divide-y divide-border-muted">{notices.length?notices.map(n=><li key={n.id} className={`flex items-start gap-md p-md ${n.is_read?"":"bg-indigo-accent/5"}`}><span className={`mt-2 h-2 w-2 rounded-full ${n.is_read?"bg-border-muted":"bg-indigo-accent"}`}/><button onClick={()=>!n.is_read&&read(n.id)} className="flex-1 text-left"><b className="block capitalize">{n.type.replaceAll("_"," ")}</b><p className="my-xs text-on-surface-variant">{n.message}</p><small>{dateTime(n.created_at)}</small></button></li>):<li className="p-xl text-center text-on-surface-variant">You&apos;re all caught up.</li>}</ul>:<div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-surface-subtle text-xs uppercase text-on-surface-variant"><tr><th className="p-md">Actor</th><th>Action</th><th>Entity</th><th>Timestamp</th></tr></thead><tbody className="divide-y divide-border-muted">{logs.map(x=><tr key={x.id}><td className="p-md font-semibold">{x.actor}</td><td>{x.action}</td><td className="capitalize">{x.entity_type.replaceAll("_"," ")}</td><td className="pr-md text-sm text-on-surface-variant">{dateTime(x.timestamp)}</td></tr>)}</tbody></table></div>}</section></div>}
